### ISSUE TITLE
pixi support

### ISSUE THREAD

**Issue by you06** [AlexanderKanakis/RPGMV#1]
RPG Maker MV use Pixi.js as its render engine. Can this plugin work with pixi.js like [pixi-spine](https://github.com/pixijs/pixi-spine) ?

[pixi-spine usage demo](https://pixijs.io/examples/#/spine/dragon.js)

If spriter plugin can't work with pixi.js, I want to help migrate this plugin to pixi.js.

**Comment by AlexanderKanakis** [comment]
Just to make it clear, you are asking whether or not spriter plugin can work on raw pixi.js, independently from MV?

**Comment by you06** [comment]
> Just to make it clear, you are asking whether or not spriter plugin can work on raw pixi.js, independently from MV?

Yes.

**Comment by AlexanderKanakis** [comment]
Unfortunately, no. Spriter plugin is very heavily based on MV classes and functions.

My one concern is that spriter plugin is meant to work interactively instead of just displaying the animation. Animations can be manipulated so that skins can be changed, animations can be attached to other animations, etc. This does not make the migration impossible, but it does make it trickier.

You are free to attempt to migrate it! But when in comes to the matter of my help, it depends on what you would require. Unfortunately, I am quite occupied from several fronts, one of them being the creation of additional spriter plugin content for MV. I cannot actively play a large role in the migration, **at least not at the moment**. But if it's a matter of advice, logic and some secondary help, I will be more than happy to help out!

**Comment by you06** [comment]
I will try to migrate it, or make a spriter pro version of pixi-spine which can be quite different from RPG Maker plugin. Thanks for your advices, AlexanderKanakis!

**Comment by AlexanderKanakis** [comment]
Feel free to reach out in case you have any questions. The guys at Brashmonkey will also be very supportive, if you ask them.
